services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wedding123
      POSTGRES_DB: wedding_registry
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wedding_registry"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
